### ISSUE TITLE
Separate behavior and component

### ISSUE THREAD

**Issue by samdark** [weblement/yii2#1]
These aren't related so it's preferred to have two separate extensions.

**Comment by Locustv2** [comment]
@samdark I actually had plans to add more reusable components etc which is why i made this repo to put everything in. Should i create an individual extension for each of them?

**Comment by samdark** [comment]
Yes. That's much better since developers tend to have only actually used libraries to their projects.

**Comment by Locustv2** [comment]
That's a point. I'll do that instead

**Comment by Locustv2** [comment]
Moved to https://github.com/Locustv2/yii2-linkable-behavior
